apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  dnsNames:
  - argocd.gateway-7e334ca5.nip.io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: letsencrypt-prod-tls