apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  dnsNames:
  - argocd.gateway-7e334ca5.nip.io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  secretName: letsencrypt-staging-tls