name: Build Airflow Container Image
on: 
  pull_request:
    branches:
      - main
    paths:
      - 'docker/airflow/**'
jobs:
  build_image:
    uses: ./.github/workflows/workflow-build-image.yml
    with:
      context: 'docker/airflow'
      push: false
      image_name: airflow
    secrets: inherit

