name: Publish Airflow Container Image
on: 
  push:
    branches:
      - main
    paths:
      - './docker/airflow/Dockerfile'
jobs:
  build_image:
    uses: ./.github/workflows/workflow-build-image.yml
    with:
      dockerfile_path: './docker/airflow/Dockerfile'
      push: true
      image_name: airflow

