name: Publish Airflow Container Image
on: 
  push:
    branches:
      - main
    paths:
      - 'docker/airflow/**'
jobs:
  build_image:
    uses: ./.github/workflows/workflow-build-image.yml
    with:
      context: 'docker/airflow'
      push: true
      image_name: airflow
    secrets: inherit
